# Generated by Django 6.0 on 2025-12-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_local_qkd_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='localqkdkey',
            new_name='crypto_loca_request_d99eca_idx',
            old_name='crypto_loc_request_9113ed_idx',
        ),
        migrations.RenameIndex(
            model_name='localqkdkey',
            new_name='crypto_loca_expires_1b8979_idx',
            old_name='crypto_loc_expires_a707f9_idx',
        ),
        migrations.RenameIndex(
            model_name='localqkdkey',
            new_name='crypto_loca_state_5b0221_idx',
            old_name='crypto_loc_state_7c1b8e_idx',
        ),
    ]
