# Generated by Django 6.0 on 2025-12-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('draft', 'Draft'), ('trash', 'Trash')], db_index=True, default='inbox', max_length=10),
        ),
    ]
