# Generated by Django 6.0 on 2025-12-08 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_accounts', '0003_emailaccount_sync_count_and_more'),
        ('mail', '0002_attachment_encryption_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(db_index=True)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_metadata',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='email',
            name='emails_user_id_838581_idx',
        ),
        migrations.RemoveIndex(
            model_name='email',
            name='emails_message_7b58ef_idx',
        ),
        migrations.AlterField(
            model_name='email',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_legacy', to='email_accounts.emailaccount'),
        ),
        migrations.AlterField(
            model_name='email',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='email',
            table='emails_legacy',
        ),
        migrations.AddField(
            model_name='emailmetadata',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_metadata', to='email_accounts.emailaccount'),
        ),
        migrations.AddField(
            model_name='emailmetadata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_metadata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailmetadata',
            index=models.Index(fields=['user', 'account', '-sent_at'], name='email_metad_user_id_5d70af_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmetadata',
            index=models.Index(fields=['message_id'], name='email_metad_message_a89639_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmetadata',
            index=models.Index(fields=['is_read', 'is_starred'], name='email_metad_is_read_7edcd2_idx'),
        ),
    ]
