"""
Django settings for qutemail project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import sys
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add apps directory to path
sys.path.insert(0, str(BASE_DIR / 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-zq1m$d(rdf28ho_d)hwk9x3lrj!p1(*%8sifff!p-^y3^)qh%8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'corsheaders',
    
    # Local apps
    'apps.accounts',
    'apps.mail',
    'apps.qkd',
    'apps.crypto',
    'apps.infra',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'qutemail.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'qutemail.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL', default='sqlite:///db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
CORS_ALLOW_CREDENTIALS = True

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Redis Configuration
REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/0')

# QKD Configuration
QKD_KM_URL = config('QKD_KM_URL', default='http://localhost:8080')
QKD_SIMULATOR_MODE = config('QKD_SIMULATOR_MODE', default=True, cast=bool)

# Email Configuration (Client - for sending to external SMTP)
SMTP_HOST = config('SMTP_HOST', default='localhost')
SMTP_PORT = config('SMTP_PORT', default=587, cast=int)
SMTP_USE_TLS = config('SMTP_USE_TLS', default=True, cast=bool)
IMAP_HOST = config('IMAP_HOST', default='localhost')
IMAP_PORT = config('IMAP_PORT', default=993, cast=int)
IMAP_USE_SSL = config('IMAP_USE_SSL', default=True, cast=bool)

# SMTP Server Configuration (Our server for receiving/sending emails)
EMAIL_DOMAIN = config('EMAIL_DOMAIN', default='qutemail.com')

# Server hostnames and ports
SMTP_SERVER_HOSTNAME = config('SMTP_SERVER_HOSTNAME', default='0.0.0.0')
SMTP_MTA_PORT = config('SMTP_MTA_PORT', default=25, cast=int)
SMTP_MSA_PORT = config('SMTP_MSA_PORT', default=587, cast=int)
SMTP_SMTPS_PORT = config('SMTP_SMTPS_PORT', default=465, cast=int)

# TLS/SSL Certificates (for secure SMTP)
SMTP_TLS_CERT = config('SMTP_TLS_CERT', default='/etc/letsencrypt/live/yourdomain.com/fullchain.pem')
SMTP_TLS_KEY = config('SMTP_TLS_KEY', default='/etc/letsencrypt/live/yourdomain.com/privkey.pem')

# Email Size Limits
SMTP_MAX_MESSAGE_SIZE = config('SMTP_MAX_MESSAGE_SIZE', default=25 * 1024 * 1024, cast=int)  # 25MB

# Rate Limiting (per hour)
SMTP_RATE_LIMIT_PER_IP = config('SMTP_RATE_LIMIT_PER_IP', default=100, cast=int)
SMTP_RATE_LIMIT_PER_USER = config('SMTP_RATE_LIMIT_PER_USER', default=500, cast=int)

# Mailbox Configuration
MAILBOX_DEFAULT_QUOTA_GB = config('MAILBOX_DEFAULT_QUOTA_GB', default=5, cast=int)

# Email Retention Policy
EMAIL_RETENTION_DAYS = config('EMAIL_RETENTION_DAYS', default=365, cast=int)

# DKIM Configuration (for email authentication)
DKIM_SELECTOR = config('DKIM_SELECTOR', default='mail')
DKIM_PRIVATE_KEY_PATH = config('DKIM_PRIVATE_KEY_PATH', default='/etc/dkim/private.key')
