# Generated by Django 6.0 on 2025-12-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='provider',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('yahoo', 'Yahoo'), ('qutemail', 'QuTeMail'), ('custom', 'Custom IMAP/SMTP')], max_length=20),
        ),
    ]
