# Generated by Django 6.0 on 2025-12-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_accounts', '0002_alter_emailaccount_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='sync_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='total_emails_cached',
            field=models.IntegerField(default=0),
        ),
    ]
