# Generated by Django 5.0.1 on 2025-11-29 13:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='email_settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_address', models.EmailField(help_text="User's email address (username@qutemail.local)", max_length=254, unique=True)),
                ('display_name', models.CharField(help_text='Display name for outgoing emails', max_length=255)),
                ('signature', models.TextField(blank=True, help_text='Email signature appended to outgoing emails')),
                ('smtp_password_encrypted', models.BinaryField(default=bytes, help_text='Encrypted SMTP password')),
                ('imap_password_encrypted', models.BinaryField(default=bytes, help_text='Encrypted IMAP password')),
                ('auto_fetch_interval', models.IntegerField(default=60, help_text='IMAP auto-fetch interval in seconds (0 to disable)')),
                ('enable_qkd_encryption', models.BooleanField(default=True, help_text='Enable QKD encryption for outgoing emails by default')),
                ('storage_quota_mb', models.IntegerField(default=1024, help_text='Storage quota in megabytes (0 for unlimited)')),
                ('storage_used_bytes', models.BigIntegerField(default=0, help_text='Current storage usage in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last time emails were synced from IMAP', null=True)),
            ],
            options={
                'verbose_name': 'User Email Settings',
                'verbose_name_plural': 'User Email Settings',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('trash', 'Trash'), ('spam', 'Spam'), ('archive', 'Archive')], db_index=True, default='inbox', max_length=20)),
                ('message_id', models.CharField(db_index=True, help_text='Unique RFC822 Message-ID', max_length=255, unique=True)),
                ('in_reply_to', models.CharField(blank=True, help_text='Message-ID of email being replied to', max_length=255, null=True)),
                ('references', models.TextField(blank=True, help_text='Space-separated list of Message-IDs in thread', null=True)),
                ('subject', models.CharField(max_length=998)),
                ('from_address', models.EmailField(max_length=254)),
                ('to_addresses', models.JSONField(default=list, help_text='List of recipient email addresses')),
                ('cc_addresses', models.JSONField(blank=True, default=list, help_text='List of CC email addresses')),
                ('bcc_addresses', models.JSONField(blank=True, default=list, help_text='List of BCC email addresses')),
                ('body_text', models.TextField(blank=True, help_text='Plain text body')),
                ('body_html', models.TextField(blank=True, help_text='HTML body')),
                ('raw_email', models.BinaryField(blank=True, help_text='Complete RFC822 message (binary)', null=True)),
                ('is_encrypted', models.BooleanField(db_index=True, default=False, help_text='Whether email is QKD encrypted')),
                ('qkd_key_id', models.CharField(blank=True, db_index=True, help_text='QKD key ID for encryption/decryption', max_length=64, null=True)),
                ('encryption_algorithm', models.CharField(blank=True, default='AES-256-GCM', help_text='Encryption algorithm used', max_length=50, null=True)),
                ('encryption_nonce', models.CharField(blank=True, help_text='Hex-encoded encryption nonce', max_length=128, null=True)),
                ('encryption_tag', models.CharField(blank=True, help_text='Hex-encoded authentication tag', max_length=128, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('received', 'Received')], db_index=True, default='draft', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_starred', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('has_attachments', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Original email date from headers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('size', models.IntegerField(default=0, help_text='Total size of email including attachments in bytes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(help_text='MIME content type', max_length=100)),
                ('size', models.IntegerField(help_text='Size in bytes')),
                ('data', models.BinaryField(help_text='Binary attachment data stored in PostgreSQL')),
                ('checksum', models.CharField(help_text='SHA-256 checksum for integrity verification', max_length=64)),
                ('content_id', models.CharField(blank=True, help_text='Content-ID for inline images', max_length=255, null=True)),
                ('is_inline', models.BooleanField(default=False, help_text='Whether attachment is inline (e.g., embedded image)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.email')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retry', 'Retry'), ('bounced', 'Bounced'), ('received', 'Received'), ('parsed', 'Parsed'), ('encrypted', 'Encrypted'), ('decrypted', 'Decrypted'), ('decryption_failed', 'Decryption Failed'), ('qkd_key_requested', 'QKD Key Requested'), ('qkd_key_retrieved', 'QKD Key Retrieved')], db_index=True, max_length=30)),
                ('message', models.TextField(help_text='Human-readable log message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event metadata')),
                ('error_code', models.CharField(blank=True, help_text='Error code if applicable', max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Detailed error message', null=True)),
                ('traceback', models.TextField(blank=True, help_text='Python traceback for debugging', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mail.email')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (5, 'Normal'), (10, 'High'), (15, 'Urgent')], db_index=True, default=5, help_text='Higher priority emails are processed first')),
                ('attempts', models.IntegerField(default=0, help_text='Number of send attempts made')),
                ('max_attempts', models.IntegerField(default=5, help_text='Maximum number of send attempts before giving up')),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When to send this email')),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='When to retry after a failed attempt', null=True)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Whether this queue entry is currently being processed')),
                ('locked_at', models.DateTimeField(blank=True, help_text='When the queue entry was locked', null=True)),
                ('locked_by', models.CharField(blank=True, help_text='Celery worker ID that locked this entry', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='mail.email')),
            ],
            options={
                'verbose_name': 'Email Queue Entry',
                'verbose_name_plural': 'Email Queue Entries',
                'ordering': ['-priority', 'scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code (e.g., #3B82F6)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_labels', to='mail.email')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_labels', to='mail.label')),
            ],
            options={
                'verbose_name': 'Email Label',
                'verbose_name_plural': 'Email Labels',
            },
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', 'folder', '-date'], name='mail_email_user_id_dac291_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', 'is_read', '-date'], name='mail_email_user_id_282f77_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['status', 'created_at'], name='mail_email_status_62452f_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['qkd_key_id'], name='mail_email_qkd_key_4e9a91_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', 'is_deleted'], name='mail_email_user_id_44eea3_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['email', 'is_inline'], name='mail_attach_email_i_83fe99_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email', '-created_at'], name='mail_emaill_email_i_b58b06_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['event_type', '-created_at'], name='mail_emaill_event_t_4397b8_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['-created_at'], name='mail_emaill_created_f184cd_idx'),
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['scheduled_at', 'is_locked'], name='mail_emailq_schedul_69af1a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['-priority', 'scheduled_at'], name='mail_emailq_priorit_91b401_idx'),
        ),
        migrations.AddIndex(
            model_name='emailqueue',
            index=models.Index(fields=['is_locked', 'scheduled_at'], name='mail_emailq_is_lock_b2f31e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='emaillabel',
            index=models.Index(fields=['email', 'label'], name='mail_emaill_email_i_84896b_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillabel',
            index=models.Index(fields=['label', 'created_at'], name='mail_emaill_label_i_54277e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emaillabel',
            unique_together={('email', 'label')},
        ),
    ]
